name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: Integration and Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.12
      - name: Build and run tests for Python 3.6
        run: |
          ./scripts/install.sh
          python scripts/run-tests.py
      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - name: Build and run tests for Python 3.7
        run: |
          ./scripts/install.sh
          python scripts/run-tests.py
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6
      - name: Build and run tests for Python 3.8
        run: |
          ./scripts/install.sh
          python scripts/run-tests.py
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: Build and run tests for Python 3.9
        run: |
          ./scripts/install.sh
          python scripts/run-tests.py
  acceptance:
    name: Acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Checkout mock-server action
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: github-actions
          token: ${{ secrets.GH_TOKEN }}
          path: deployment-tools
      - name: Run mock server action
        uses: ./deployment-tools/actions/mock-server
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install Python dependencies and run acceptance tests
        run: |
            cp sdk-specifications/features/access/authorization-failure-reporting.feature tests/acceptance/pam
            cp sdk-specifications/features/access/grant-token.feature tests/acceptance/pam
            cp sdk-specifications/features/access/revoke-token.feature tests/acceptance/pam

            sudo pip3 install -r requirements-dev.txt
            behave --junit tests/acceptance/pam
      - name: Expose acceptance tests reports
        uses: actions/upload-artifact@v2
        with:
          name: acceptance-test-reports
          path: ./reports
